### ISSUE TITLE
link error when building with cmake

### ISSUE THREAD

**Issue by gaaned92** [LibRaw/LibRaw-cmake#1]
hello
I am trying to build libraw 0.18 with cmake . At linking I get this error message:
    [  3%] Linking CXX shared library libraw_r.dll
    [  6%] Linking CXX shared library libraw.dll
    CMakeFiles/raw.dir/objects.a(libraw_cxx.cpp.obj):libraw_cxx.cpp:(.text+0x4aa1): undefined    reference to `uncompress'
collect2.exe: error: ld returned 1 exit status
CMakeFiles/raw_r.dir/objects.a(libraw_cxx.cpp.obj):libraw_cxx.cpp:(.text+0x4aa1): undefined reference to`uncompress'
collect2.exe: error: ld returned 1 exit status
CMakeFiles/raw_r.dir/build.make:228 : la recette pour la cible « libraw_r.dll » a échouée
make[2]: **\* [libraw_r.dll] Erreur 1
CMakeFiles/Makefile2:326 : la recette pour la cible « CMakeFiles/raw_r.dir/all » a échouée
make[1]: **\* [CMakeFiles/raw_r.dir/all] Erreur 2
make[1]: **\* Attente des tâches non terminées....
CMakeFiles/raw.dir/build.make:228 : la recette pour la cible « libraw.dll » a échouée
make[2]: **\* [libraw.dll] Erreur 1
CMakeFiles/Makefile2:252 : la recette pour la cible « CMakeFiles/raw.dir/all » a échouée
make[1]: **\* [CMakeFiles/raw.dir/all] Erreur 2
Makefile:127 : la recette pour la cible « all » a échouée
make: **\* [all] Erreur 2

I don't know if it is the good place to post this error.
Thanks in advance
André

**Comment by LibRaw** [comment]
LibRaw-cmake is completely user contributed. It is moved away of Libraw main repo because Libraw team is unable to maintain cmake builds.

You may propose a patch and I'll accept it without any review.

**Comment by LibRaw** [comment]
followup: looks like you need to ad libz to libs

**Comment by letmaik** [comment]
Just to confirm, the build also fails on travis ci currently: https://travis-ci.org/LibRaw/LibRaw-cmake/builds/92978201#L208 @LibRaw Can you give some more details about what you mean? I couldn't find `libz` when searching through the main repository.

**Comment by LibRaw** [comment]
libz is also known as zlib.

**Comment by letmaik** [comment]
Is this a new dependency for libraw? Since which version?

Am 20.01.2016 um 11:07 schrieb LibRaw LLC:

**Comment by LibRaw** [comment]
Yes, zlib is a new dependency in current development branch, but not in any stable releases

**Comment by gaaned92** [comment]
I was able to build libraw 0.17 with your Cmake file  on win32. (it fails miserably with the configure file)

I tried again with the development branch 0.18 from github. As I am not a dev but a end user, I tried "to ad libz to libs" as suggested by LibRaw. I included a "findpackage (zlib required)"  in the cmake file. libz is found but link fails again with same error.
note : I wonder why the libraw team choose the configure way and not the cmake way  for an app which, first is not a basic package and second will run exclusively on modern  linux, windows and ios systems.

I cannot really help you as I am not proficient enough and I thank you for your work.

**Comment by LibRaw** [comment]
You may build LibRaw on Win32 by using
nmake -f Makefile.msvc - for Visual Studio builds
make -f Makefile.mingw - for mingw build

Cmake is unsupported by LibRaw team (and not included in Libraw package), use on your own risk

**Comment by letmaik** [comment]
I had a look at the code and saw that zlib is needed for the DNG deflate format only at the moment. Maybe to ease the transition, the support for that could be made optional like for the lossy DNG format (jpeglib). What do you think @LibRaw?

**Comment by LibRaw** [comment]
We'll think about it. 
Anyway, LibRaw 0.18-201511 is current snapshot from our internal repository. No plans to publish another snapshot within next 2-3 months.

**Comment by LibRaw** [comment]
as of LibRaw-0.18-beta1, zlib is optional
