### ISSUE TITLE
Error compiling with new sample file mem_image_sample.cpp

### ISSUE THREAD

**Issue by paulasquin** [LibRaw/LibRaw-cmake#11]
Hi !

This modification https://github.com/LibRaw/LibRaw-cmake/commit/4e27fc6bb198631df816a32218c58e310b4879cd 
is creating an error when compiling older libraw version such as 0.19.0
Shouldn't libraw-cmake also provides release to ensure compatibility?

```
CMake Error at CMakeLists.txt:647 (ADD_EXECUTABLE):
  Cannot find source file:

    samples/mem_image_sample.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx
Call Stack (most recent call first):
  CMakeLists.txt:674 (LIBRAW_BUILD_SAMPLES)


CMake Error at CMakeLists.txt:647 (ADD_EXECUTABLE):
  No SOURCES given to target: mem_image_sample
Call Stack (most recent call first):
  CMakeLists.txt:674 (LIBRAW_BUILD_SAMPLES)
```
Thanks :)

**Comment by letmaik** [comment]
The easiest fix would be to support both the old and new file name by checking if the file exists. If you’re comfortable with cmake feel free to submit a pull request, otherwise I can fix it myself in a while.

**Comment by paulasquin** [comment]
Hi @letmaik 
Here is the Pull Request : https://github.com/LibRaw/LibRaw-cmake/pull/12

Checked successfully on libraw 0.19.0 and 0.19.5

Bests!

PS : could you tag the version resulting of this Pull Request? Thanks!

**Comment by letmaik** [comment]
I merged your fix, thanks for that. I'd prefer not to start introducing version numbers simply due to the additional overhead. It shouldn't be a problem though as you can pin by using the commit hash instead.
