### ISSUE TITLE
libraw_r is not built with thread support

### ISSUE THREAD

**Issue by madebr** [LibRaw/LibRaw-cmake#19]
See these lines:
https://github.com/LibRaw/LibRaw-cmake/blob/23cbe3c7bf9c39ae200dd3877b8dade233cce7e9/CMakeLists.txt#L515-L521

These will apply these compile definitions to the source files, which are used for both libraw and libraw_r.

These lines should get replaced with:
`target_compile_definitions(libraw PRIVATE LIBRAW_NOTHREADS)`
and moved below `add_library(raw ...)`.

**Comment by letmaik** [comment]
The `LIBRAW_NOTHREADS` definition doesn't influence whether threads are used or not but rather whether the library is built thread-safe or not. You are right though that the current logic is incorrect and this should only be applied to the non-threaded variant `raw`. Can you raise a PR?
