### ISSUE TITLE
FindLibRaw with LibRaw-0.20.2

### ISSUE THREAD

**Issue by Alexey-Danilchenko** [LibRaw/LibRaw-cmake#21]
FindLibRaw is written with reliance on pkg-config. Whilst this is prevailing thing for Linux - vast majority of LibRaw usage is not there and building CMake projects on Windows and MacOS requires decipherung cryptic errors about pkg-config not found. This module really should be written without being platform specific pain

**Comment by letmaik** [comment]
PR welcome :)

**Comment by Alexey-Danilchenko** [comment]
Sorry, no idea what it means.

**Comment by letmaik** [comment]
PR means pull request. What I'm saying is, this project does not have a core set of developers, so it's up to contributers to help improve it. Keep in mind that these CMake files are actually used for Windows builds already, see https://github.com/letmaik/rawpy/blob/244eb3e97684fbe40864162ab7b11c468d06e0ec/setup.py#L188. So pkgconfig doesn't seem like a mandatory requirement.

**Comment by Alexey-Danilchenko** [comment]
>Keep in mind that these CMake files are actually used for Windows builds already

Really? Do me a favour then - try to run CMakeLists.txt with something like
find_package(LibRaw REQUIRED)
On Windows with just VC++ installed and let me know how it can possibly work.

I am not talking about building scripts (I am building LibRaw with makefiles just fine) - which is why I specifically referred to FinsLibRaw as a problem.  Sure I will fix it in my project suitable to my needs. Whether it will be generic enough to do a pull request remains to be seen.

**Comment by letmaik** [comment]
Without any error messages it's hard to diagnose issues. Please be as detailed as possible.

**Comment by Alexey-Danilchenko** [comment]
Sure. The below is caused by find_package(LibRaw REQUIRED) (that's on MacOS as I am working on it now - Windows will reproduce in the evening if required but essentially the same).

cmake] -- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
[cmake] CMake Error at /Applications/CMake.app/Contents/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
[cmake]   Could NOT find LibRaw (missing: LibRaw_LIBRARIES LibRaw_INCLUDE_DIR)
[cmake] Call Stack (most recent call first):
[cmake]   /Applications/CMake.app/Contents/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:577 (_FPHSA_FAILURE_MESSAGE)
[cmake]   cmake/modules/FindLibRaw.cmake:85 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
[cmake]   CMakeLists.txt:24 (find_package)

**Comment by letmaik** [comment]
This just says it couldn't find libraw, nothing to do with pkgconfig. Please see the link I posted earlier on how to invoke CMake.

**Comment by Alexey-Danilchenko** [comment]
Thanks - sorted.

**Comment by Alexey-Danilchenko** [comment]
This works fine on MacOS, Linux but with Windows version of LibRaw 0.20.2 still does not. It partially finds it but then breaks when checking libraries. Below are the log of calling find_package(LibRaw REQUIRED) with CMake 3.18 on Microsoft VC++ 2019 x64. The errors are the same whether I build LibRaw myself with MSVC make file or download officially released binary version of LibRaw for Windows.

[cmake] -- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
[cmake] CMake Error at C:/Development/CMake/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
[cmake]   Could NOT find LibRaw (missing: LibRaw_LIBRARIES) (found version "0.20.2")
[cmake] Call Stack (most recent call first):
[cmake]   C:/Development/CMake/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
[cmake]   cmake/modules/FindLibRaw.cmake:85 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
[cmake]   CMakeLists.txt:32 (find_package)

**Comment by Alexey-Danilchenko** [comment]
This repository's FindLibRaw.cmake does not work properly with MSVC++ build of LibRaw. Simply because it looks up raw and raw_r libraries and on Windows cmake library prefix is empty. Also none of the standard LibRaw builds (non-cmake) does distinguish between debug and release versions.

In the end I decided to write my own FindLibRaw module suitable to work with standard LibRaw - either released binary or built from sources. It also uses imported libraries which makes it easier to use imo. Anyway, if interested my module is available in [my repository here](https://github.com/Alexey-Danilchenko/Kodak-DCS-Tools/tree/master/sources/DCSRemap/cmake/modules)
